--Write the query that returns the most and least shopped brands for each city using cross apply.


SELECT
C.CITY, ORDERINFO_MAX.BRAND, ORDERINFO_MAX.TOTALPRICE, ORDERINFO_MIN.BRAND, ORDERINFO_MIN.TOTALPRICE
FROM CITIES C
CROSS APPLY (
	SELECT
	TOP 1
	I.BRAND, SUM(OD.LINETOTAL) AS TOTALPRICE
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS ORDERINFO_MAX

CROSS APPLY (
	SELECT
	TOP 1
	I.BRAND, SUM(OD.LINETOTAL) AS TOTALPRICE
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) AS ORDERINFO_MIN


