--Write the query that returns the date, city and address of each user's last purchase with cross apply.


SELECT
U1.ID, U1.NAMESURNAME, ORDER_INFO.*
FROM USERS U1
CROSS APPLY
(
	SELECT
	TOP 1
	O.DATE_, A.ADDRESSTEXT, C.CITY, T.TOWN, D.DISTRICT,
	I.ITEMNAME, O.TOTALPRICE
	FROM ORDERS O
	JOIN USERS U ON U.ID = O.USERID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	JOIN TOWNS T ON T.ID = A.TOWNID
	JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE U.ID = U1.ID
	ORDER BY O.DATE_ DESC, O.ID DESC
) AS ORDER_INFO

