--Bring records for each month where the month of the order date and the month of the invoice date are different.


SELECT 
DATENAME(MONTH, O.DATE_) AS ORDER_MONTH,
COUNT(DATENAME(MONTH, I.DATE_)) AS INVOICE_NEXT_MONTH_TOTAL_SALES
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID = O.ID
WHERE DATENAME(MONTH, O.DATE_) <> DATENAME(MONTH, I.DATE_)
GROUP BY DATENAME(MONTH, O.DATE_), DATEPART(MONTH, O.DATE_)
ORDER BY DATEPART(MONTH, O.DATE_)

