--Write the query that shows how much shopping was done by hour.


SELECT 
DATEPART(HOUR, DATE_) AS HOUR_,
CONVERT(INT,ROUND(SUM(TOTALPRICE), 0)) AS TOPLAMTUTAR,
COUNT(ID) AS SIPARISSAYISI
FROM ORDERS

GROUP BY DATEPART(HOUR, DATE_)
ORDER BY 1