--Write the query that returns the total shipping time for each order.



SELECT 
O.ID AS SIPARISNO, U.NAMESURNAME AS KULLANICI, C.CITY AS SEHIR,
O.DATE_ AS SIPARISTARIHI, I.DATE_ AS FATURATARIHI,
DATEDIFF(HOUR, O.DATE_, I.DATE_) AS TESLIMSURESI
FROM ORDERS AS O
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN INVOICES I ON I.ORDERID = O.ID
ORDER BY 1