--Enter the total sales for each product in units and total turnover. 
--Also, write the query that calculates the profit and loss based on the lowest, 
--highest, average sales, and current price for each product.



SELECT 
I.ITEMCODE, I.ITEMNAME, I.UNITPRICE,
SUM(OD.AMOUNT) AS TOTAL_AMOUNT,
CONVERT(INT,SUM(OD.LINETOTAL)) AS TOTAL_PRICE,
ROUND(MIN(OD.UNITPRICE),2) AS MIN_PRICE,
ROUND(MAX(OD.UNITPRICE),2) AS MAX_PRICE,
ROUND(AVG(OD.UNITPRICE),2) AS AVG_PRICE,
SUM(I.UNITPRICE * OD.AMOUNT) AS LIST_PRICE_SALE,
ROUND((SUM(OD.LINETOTAL) - SUM(I.UNITPRICE * OD.AMOUNT)),2) AS PROFIT_LOSS,

ROUND(100 * (SUM(OD.LINETOTAL) - SUM(I.UNITPRICE * OD.AMOUNT))
/
SUM(I.UNITPRICE * OD.AMOUNT),2) AS PROFIT_LOSS_PERCENT

FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.ITEMCODE, I.ITEMNAME, I.UNITPRICE
ORDER BY 1