--Write the query that returns the sales of cities by month.

SELECT
C.CITY,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 1
) AS JANUARY,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 2
) AS FEBRUARY,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 3
) AS MARCH,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 4
) AS APRIL,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 5
) AS MAY,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 6
) AS JUNE,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 7
) AS JULY,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 8
) AS AUGUST,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 9
) AS SEPTEMBER,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 10
) AS OCTOBER,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 11
) AS NOVEMBER,
(
	SELECT 
	SUM(O.TOTALPRICE) 
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND DATEPART(MONTH, O.DATE_) = 12
) AS DECEMBER

FROM CITIES C

