--Write the query that returns users with more than two addresses using the subquery method.


--JOIN METHOD

SELECT 
U.NAMESURNAME,
COUNT(A.ID) AS ADDRESS_NUMBER
FROM USERS U
JOIN ADDRESS A ON A.USERID = U.ID
GROUP BY U.NAMESURNAME, U.ID
HAVING COUNT(A.ID) > 2
ORDER BY 2 DESC


--SUBQUERY METHOD

SELECT
U.NAMESURNAME,
(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) AS ADDRESS_NUMBER
FROM USERS U
WHERE (SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) > 2


--DYNAMIC VIEW METHOD
SELECT * FROM
(
	SELECT
	U.NAMESURNAME,
	(SELECT COUNT(*) FROM ADDRESS WHERE USERID = U.ID) AS ADDRESS_NUMBER
	FROM USERS U
) T
WHERE ADDRESS_NUMBER > 2
