--Write the query that returns the best-selling category and the least-selling category for each brand.


SELECT 
DISTINCT BRAND,
(
	SELECT TOP 1
	I.CATEGORY1
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS THE_BEST_SELLING,

(
	SELECT 
	TOP 1
	SUM(OD.LINETOTAL)
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS TOTAL_PRICE,
(
	SELECT TOP 1
	I.CATEGORY1
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) ASC
) AS THE_LEAST_SELLING,

(
	SELECT 
	TOP 1
	SUM(OD.LINETOTAL)
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE BRAND = I1.BRAND
	GROUP BY I.CATEGORY1
	ORDER BY SUM(OD.LINETOTAL) ASC
) AS TOTAL_PRICE
FROM ITEMS I1





