--Write a query that returns the date, city, and address where each user last shopped.


SELECT
U.ID, U.NAMESURNAME,
(
	SELECT MAX(DATE_) FROM ORDERS O WHERE USERID = U.ID
) AS LAST_DATE,

(
	SELECT
	TOP 1
	C.CITY
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	WHERE O.USERID = U.ID
	ORDER BY DATE_ DESC
) AS LAST_CITY,

(
	SELECT
	TOP 1
	A.ADDRESSTEXT
	FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	JOIN CITIES C ON C.ID = A.CITYID
	WHERE O.USERID = U.ID
	ORDER BY DATE_ DESC
) AS LAST_ADDRESS

FROM USERS U
ORDER BY 1 


