--For each city, write the query that returns the most and least shopped brands.


SELECT
C.CITY,
(
	SELECT
	TOP 1
	I.BRAND
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS MOST_BRAND,
(
	SELECT
	TOP 1
	SUM(OD.LINETOTAL) AS TOTAL_PRICE
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS TOTAL_PRICE,
(
	SELECT
	TOP 1
	I.BRAND
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) 
) AS MIN_BRAND,

(
	SELECT
	TOP 1
	SUM(OD.LINETOTAL)
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) 
) AS TOTAL_PRICE

FROM CITIES C


