--Write the query that returns the most and least shopped categories for each city.


SELECT
C.CITY,
(
	SELECT
	TOP 1
	I.CATEGORY2
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS MOST_CAGETORY,
(
	SELECT
	TOP 1
	SUM(OD.LINETOTAL) AS TOTAL_PRICE
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS TOTAL_PRICE,
(
	SELECT
	TOP 1
	I.CATEGORY2
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) 
) AS MIN_CATEGORY,

(
	SELECT
	TOP 1
	SUM(OD.LINETOTAL)
	FROM ORDERS O
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS I ON I.ID = OD.ITEMID
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID
	GROUP BY I.CATEGORY2
	ORDER BY SUM(OD.LINETOTAL) 
) AS TOTAL_PRICE

FROM CITIES C



