--Write the query that brings up the sales figures for the food, detergent and cleaning categories in which city.


SELECT
C.CITY,
(
	SELECT SUM(OD.LINETOTAL) FROM ORDERS AS O
		JOIN ORDERDETAILS AS OD ON OD.ORDERID = O.ID
		JOIN ADDRESS  AS A ON A.ID = O.ADDRESSID
		JOIN ITEMS AS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = 'GIDA' AND A.CITYID = C.ID
) AS FOOD_TOTAL,
(
	SELECT SUM(OD.LINETOTAL) FROM ORDERS AS O
		JOIN ORDERDETAILS AS OD ON OD.ORDERID = O.ID
		JOIN ADDRESS  AS A ON A.ID = O.ADDRESSID
		JOIN ITEMS AS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = 'DETERJAN' AND A.CITYID = C.ID
) AS DETERGENT_TOTAL,
(
	SELECT SUM(OD.LINETOTAL) FROM ORDERS AS O
		JOIN ORDERDETAILS AS OD ON OD.ORDERID = O.ID
		JOIN ADDRESS  AS A ON A.ID = O.ADDRESSID
		JOIN ITEMS AS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = 'TEMIZLIK' AND A.CITYID = C.ID
) AS CLEANING_TOTAL
FROM CITIES AS C

