--Write a query that returns users with more than two addresses in the same city.

SELECT * FROM
(
SELECT 
U.ID, U.NAMESURNAME,
(SELECT COUNT(ID) FROM ADDRESS WHERE USERID = U.ID) AS TOTAL_ADDRESS_NUMBER,
(SELECT COUNT(ID) FROM ADDRESS WHERE USERID = U.ID GROUP BY CITYID HAVING COUNT(ID) > 2) AS SAME_ADDRESS_NUMBER
FROM USERS U
) T
WHERE SAME_ADDRESS_NUMBER > 2



