--JOIN

SELECT
I.ID, I.ITEMCODE, I.ITEMNAME, I.BRAND,
SUM(OD.AMOUNT) AS TOTALSALE,
SUM(OD.LINETOTAL) AS TOTALMONEY,
MIN(OD.UNITPRICE) AS MIN_PRICE,
MAX(OD.UNITPRICE) AS MAX_PRICE,
ROUND(AVG(OD.UNITPRICE), 2) AS AVG_PRICE
FROM ITEMS AS I
JOIN ORDERDETAILS AS OD ON OD.ITEMID = I.ID
GROUP BY I.ID, I.ITEMCODE, I.ITEMNAME, I.BRAND


--SUBQUERY

SELECT
I.ID, I.ITEMCODE, I.ITEMNAME, I.BRAND,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS TOTALSALE,
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS TOTALMONEY,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS MINPRICE,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS MAXPRICE,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = I.ID) AS AVGPRICE
FROM ITEMS AS I