--For each brand, write the query that returns the total number of main categories and subcategories.

SELECT 
DISTINCT(I.BRAND),
(SELECT COUNT(DISTINCT CATEGORY1) FROM ITEMS WHERE BRAND = I.BRAND) AS MAINCATEGORY,
(SELECT COUNT(DISTINCT CATEGORY2) FROM ITEMS WHERE BRAND = I.BRAND) AS SUBCATEGORY,
(SELECT COUNT(ID) FROM ITEMS WHERE BRAND = I.BRAND) AS BRAND

FROM ITEMS AS I

