--Write the query that returns the best-selling and least-sold brands for each category.


SELECT 
DISTINCT I1.CATEGORY1,
(
	SELECT TOP 1
	I.BRAND
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS THE_BEST_SELLING,
(
	SELECT TOP 1
	SUM(OD.LINETOTAL)
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) DESC
) AS TOTAL_PRICE,
(
	SELECT TOP 1
	I.BRAND
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) AS THE_LEAST_SELLING,
(
	SELECT TOP 1
	SUM(OD.LINETOTAL)
	FROM ORDERDETAILS OD
	JOIN ITEMS I ON I.ID = OD.ITEMID
	WHERE I.CATEGORY1 = I1.CATEGORY1
	GROUP BY I.BRAND
	ORDER BY SUM(OD.LINETOTAL) ASC
) AS TOTAL_PRICE
FROM ITEMS I1