SELECT  
SUM(AMOUNT) AS TOTALAMOUNT,
SUM(TOTALPRICE) AS TOTALPRICE,
MIN(TOTALPRICE) AS MIN_TOTALPRICE,
MAX(TOTALPRICE) AS MAX_TOTALPRICE,
COUNT(*) AS ROW_COUNT,
AVG(TOTALPRICE) AS AVG_TOTALPRICE,
MIN(DATE_) AS FIRSTDATE,
MAX(DATE_) AS LASTDATE

FROM SALES


WHERE CITY = 'ÝSTANBUL' AND CATEGORY1 = 'GIDA'

SELECT  
SUM(AMOUNT) AS TOTALAMOUNT,
SUM(TOTALPRICE) AS TOTALPRICE,
MIN(TOTALPRICE) AS MIN_TOTALPRICE,
MAX(TOTALPRICE) AS MAX_TOTALPRICE,
COUNT(*) AS ROW_COUNT,
AVG(TOTALPRICE) AS AVG_TOTALPRICE,
MIN(DATE_) AS FIRSTDATE,
MAX(DATE_) AS LASTDATE

FROM SALES


WHERE CITY = 'ANKARA' AND CATEGORY1 = 'GIDA'


