SELECT 

DATENAME(DW, DATE_) AS DAYNAME,
SUM(TOTALPRICE) AS TOTALSALE,
SUM(AMOUNT) AS TOTALAMOUNT,
COUNT(*) AS ROWCOUNT_

FROM SALES
GROUP BY DATEPART(DW, DATE_), DATENAME(DW, DATE_)
ORDER BY DATEPART(DW, DATE_)