SELECT
CITY,
SUM(TOTALPRICE) AS TOTALSALE,
SUM(AMOUNT) AS TOTALAMOUNT,
MIN(TOTALPRICE) AS MINTOTALPRICE,
MAX(TOTALPRICE) AS MAXTOTALPRICE,
COUNT(*) AS ROWCOUNT_,
AVG(TOTALPRICE) AS AVGTOTALPRICE,
MIN(DATE_) AS FIRSTDATE,
MAX(DATE_) AS LASTDATE

FROM SALES
WHERE CATEGORY1 = 'GIDA'
GROUP BY CITY



