SELECT 
O.ID AS ORDERID, U.USERNAME_, U.NAMESURNAME,
O.DATE_ AS ORDERDATE, O.TOTALPRICE,
A.POSTALCODE, A.ADDRESSTEXT,
C.CITY, T.TOWN,
I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2,
OD.AMOUNT, OD.UNITPRICE, OD.LINETOTAL	
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.USERID = O.ADDRESSID
JOIN ITEMS I ON I.ID = OD.ITEMID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
