SELECT
O.ID, O.DATE_, OD.AMOUNT, OD.UNITPRICE, OD.LINETOTAL,
IT.ITEMCODE, IT.ITEMNAME, IT.CATEGORY1, IT.CATEGORY2, IT.CATEGORY3
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS IT ON IT.ID = OD.ITEMID
WHERE DATE_ BETWEEN '20200101' AND '2020-01-31 23:59:59'
ORDER BY DATE_ DESC