--Write the query that brings up the top 10 best-selling products in Istanbul in the first 3 months of the year.

SELECT 
TOP 10
C.CITY AS SEHIR, I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3,
SUM(OD.AMOUNT) AS TOTALSALES, SUM(OD.LINETOTAL) AS TOTALPRICE

FROM ORDERS AS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID

WHERE C.CITY = 'ÝSTANBUL' AND O.DATE_ BETWEEN '20200101' AND '20200401'
GROUP BY C.CITY, I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3
ORDER BY SUM(OD.LINETOTAL) DESC