SELECT 
C.CITY, T.TOWN, COUNT(DISTINCT U.ID) AS NOFADDRESS
FROM ADDRESS A 
JOIN USERS U ON U.ID = A.USERID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
WHERE C.CITY = 'ÝSTANBUL'
GROUP BY C.CITY, T.TOWN
ORDER BY 3 DESC
