--List the purchases made by customers aged 20-30 in March 2020

SELECT
U.NAMESURNAME AS KULLANICIADI, DATEDIFF(YEAR, U.BIRTHDATE, GETDATE()) AS KULLANICIYAS,
C.CITY AS SEHIR, O.DATE_ AS TARIH, O.ID AS SIPARISID
FROM USERS AS U
JOIN ORDERS O ON O.USERID = U.ID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID

WHERE DATEDIFF(YEAR, U.BIRTHDATE, GETDATE()) BETWEEN 20 AND 30
AND O.DATE_ BETWEEN '2020-03-01' AND '2020-03-31 23:59:59'
ORDER BY O.DATE_